[[main]]
name = "Home"
pageRef = "/"
weight = 1

# [[main]]
# name = "About Me"
# pageRef = "about"
# weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 15

# [[main]]
# name = "Resume"
# url = "https://resume.maxanderson.tech"
# [main.params]
# target = "_blank"
