colorScheme = "custom"
enableSearch = true
enableCodeCopy = true
defaultAppearance = "light"
autoSwitchAppearance = false

[homepage]
layout = "profile"

[header]
layout = "hybrid"
showTitle = false

[footer]
showCopyright = false
showThemeAttribution = false
