colorScheme = "custom"
enableSearch = true
enableCodeCopy = true
defaultAppearance = "dark"
autoSwitchAppearance = true

[homepage]
layout = "profile"

[header]
layout = "hybrid"
showTitle = false

[footer]
showCopyright = false
showThemeAttribution = false
